name: molecular_similarity_heatmaps
channels:
- rdkit
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - rdkit
    - pip
    - pip:
        - pandas==1.0.1
        - numpy==1.18.1
        - scikit-learn==0.22.2.post1
        - mordred
        - xgboost==1.0.2
        - seaborn
        - streamlit==0.82.0
        - streamlit_tags
        - matplotlib.pyplot
